language: go
go:
- '1.11'
- tip
script:
- make ci
- make artifacts/build/release/linux/amd64/proxyclient
before_deploy: 
- make archives
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  skip_cleanup: true
  file:
  - artifacts/archives/proxyclient-darwin-amd64.tar.gz
  - artifacts/archives/proxyclient-linux-amd64.tar.gz
  - artifacts/archives/proxyclient-windows-amd64.zip
  go: '1.11'
  on:
    tags: true