language: go
go:
- '1.11'
- tip
script:
- make ci
- make artifacts/build/release/linux/amd64/proxyclient
before_deploy: 
- make archives
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bh8yIJUQcULCVtalstLRp1F5YeS0PYRRkMqa+Tegt8/Ttot3M9DNqKsbkV8+BuuHr0sIaBA0D2ym1rRdm8DgyNs5OdR5wXpv5bKXag1hbLlcmkzrnksq3RC3rCqwp66lu3RFAXiz0YGFULaA4YllaCrqGTdMfGLIkFw3uZPIfsDSsVLR+13iBpQUF0w5WZb2PHpWAkloH+p7p60UlgvO9BjZ2hsjDgbifGqQUvdYNrmlIGGiXR4v5eDRsTuFeRUsmSzTK8NaGx7GmUvTtkrceM2bRqMddHlexKSJbC2nl78jbbEkiLqayXO1EiwKpU/+0dl0J0VE6dGpuzec68zUUn/s0JCiZ/9f1IoF8eYdB7L9C0fd7Q1eV8j0ZE6wXoX+K/4Kcpic3VXHwF40MDmaHaSR09COz4LyPEl67h2hHh83GzxZcrNDSe+Ly3XIIhtAcfG40jT8YD01m/uY4xBbTqcpOYU2Gf2Wsagu1/2E+tWXyTaS8ukoO6RxIsLYVRYv65n1BpTdfpwdopbo5dtu0VS+vq53GzxNIJQ9oXXz5iMabtq05auXd7oA0AaTeRZR667QB71afHgsiG72F5WF+A8b6ayxYd7rObYQO6igrcrnyxOsIaclknvtGbTskLGvPznCogeDFAJrEvNPQx8pg0J98nFxndvcIw5mPyh0fuw=
  file:
  - artifacts/archives/proxyclient-darwin-amd64.tar.gz
  - artifacts/archives/proxyclient-linux-amd64.tar.gz
  - artifacts/archives/proxyclient-windows-amd64.zip
  go: '1.11'
  on:
    tags: true